# Importando as bibliotecas básicas

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importando o dataset

In [2]:
dados = pd.read_excel('Data_Train.xlsx')

Este dataset tem diversos dados de voos com seu preço associado

O objetivo do problema é conseguir prever o preço de um voo através dos dados disponíveis

# Olhando para os dados

In [3]:
dados

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [4]:
dados.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [5]:
dados.dtypes

Airline            object
Date_of_Journey    object
Source             object
Destination        object
Route              object
Dep_Time           object
Arrival_Time       object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
dtype: object

Temos muitas colunas categóricas neste dataset, então vamos tentar quebrar algumas, de forma a construir algumas variáveis numéricas

# Tratamento dos Dados

## Quebrando a Variável de Data

In [6]:
# 1. Converter a coluna de datas para o formato datetime do pandas
# O argumento 'format' garante que ele leia 'DD/MM/AAAA' corretamente.
dados['Date_of_Journey'] = pd.to_datetime(dados['Date_of_Journey'], format='%d/%m/%Y')

# 2. Extrair dia, mês e ano usando o acessor .dt (muito mais rápido!)
dados['day'] = dados['Date_of_Journey'].dt.day
dados['month'] = dados['Date_of_Journey'].dt.month
dados['year'] = dados['Date_of_Journey'].dt.year

# Agora as suas colunas 'day', 'month' e 'year' estão preenchidas corretamente.
print(dados.head())

       Airline Date_of_Journey    Source Destination                  Route  \
0       IndiGo      2019-03-24  Banglore   New Delhi              BLR → DEL
1    Air India      2019-05-01   Kolkata    Banglore  CCU → IXR → BBI → BLR
2  Jet Airways      2019-06-09     Delhi      Cochin  DEL → LKO → BOM → COK
3       IndiGo      2019-05-12   Kolkata    Banglore        CCU → NAG → BLR
4       IndiGo      2019-03-01  Banglore   New Delhi        BLR → NAG → DEL

  Dep_Time  Arrival_Time Duration Total_Stops Additional_Info  Price  day  \
0    22:20  01:10 22 Mar   2h 50m    non-stop         No info   3897   24
1    05:50         13:15   7h 25m     2 stops         No info   7662    1
2    09:25  04:25 10 Jun      19h     2 stops         No info  13882    9
3    18:05         23:30   5h 25m      1 stop         No info   6218   12
4    16:50         21:35   4h 45m      1 stop         No info  13302    1

   month  year
0      3  2019
1      5  2019
2      6  2019
3      5  2019
4      3  2019

In [7]:
dados

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,2019-04-27,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,2019-04-27,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,2019-03-01,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,2019-05-09,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [8]:
dados = dados.drop('Date_of_Journey', axis = 1)

## Quebrando a variável de Hora (Partida e Chegada)

In [9]:
dados["departure_hour"] = dados["Dep_Time"].str[0:2].astype(int)
dados["departure_min"]  = dados["Dep_Time"].str[3:5].astype(int)

# Cria as colunas a partir de Arrival_Time
dados["arrival_hour"] = dados["Arrival_Time"].str[0:2].astype(int)
dados["arrival_min"]  = dados["Arrival_Time"].str[3:5].astype(int)

In [10]:
dados

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,day,month,year,departure_hour,departure_min,arrival_hour,arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,9,25,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019,19,55,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019,20,45,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019,8,20,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019,11,30,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019,10,55,19,15

In [11]:
dados = dados.drop('Dep_Time', axis = 1)
dados = dados.drop('Arrival_Time', axis = 1)

In [12]:
dados

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,departure_hour,departure_min,arrival_hour,arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,9,25,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,non-stop,No info,4107,9,4,2019,19,55,22,25
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,non-stop,No info,4145,27,4,2019,20,45,23,20
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,non-stop,No info,7229,27,4,2019,8,20,11,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,non-stop,No info,12648,1,3,2019,11,30,14,10
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2 stops,No info,11753,9,5,2019,10,55,19,15

Agora que temos algumas variáveis novas na nossa base de dados, vamos tratar as variáveis categóricas

## Tratando a variável de quantidade de paradas

In [13]:
dados.Total_Stops.unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [14]:
dados['stops'] = dados['Total_Stops'].str.extract(r'(\d+)').fillna(0).astype(int)

# Verificar o resultado
print(dados[['Total_Stops', 'stops']].head())

  Total_Stops  stops
0    non-stop      0
1     2 stops      2
2     2 stops      2
3      1 stop      1
4      1 stop      1

In [15]:
dados

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,day,month,year,departure_hour,departure_min,arrival_hour,arrival_min,stops
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10,0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15,2
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,9,25,4,25,2
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30,1
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,non-stop,No info,4107,9,4,2019,19,55,22,25,0
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,non-stop,No info,4145,27,4,2019,20,45,23,20,0
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,non-stop,No info,7229,27,4,2019,8,20,11,20,0
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,non-stop,No info,12648,1,3,2019,11,30,14,10,0
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2 stops,No info,11753,9,5,2019,10,55,19,15,2

In [16]:
dados = dados.drop('Total_Stops', axis = 1)

# Aplicando o Label Encoder

In [17]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

colunas = dados.dtypes.reset_index()

categ_cols = colunas[colunas[0] == 'object']['index'].to_list()


# Preenchendo as variáveis com dados nulos com a média


for i in categ_cols:
    dados[str(i) +'_encoded'] = le.fit_transform(dados[i])
    dados = dados.drop(i,axis = 1)

In [18]:
dados

,Price,day,month,year,departure_hour,departure_min,arrival_hour,arrival_min,stops,Airline_encoded,Source_encoded,Destination_encoded,Route_encoded,Duration_encoded,Additional_Info_encoded
0,3897,24,3,2019,22,20,1,10,0,3,0,5,18,240,8
1,7662,1,5,2019,5,50,13,15,2,1,3,0,84,336,8
2,13882,9,6,2019,9,25,4,25,2,4,2,1,118,106,8
3,6218,12,5,2019,18,5,23,30,1,3,3,0,91,311,8
4,13302,1,3,2019,16,50,21,35,1,3,0,5,29,303,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,4107,9,4,2019,19,55,22,25,0,0,3,0,64,236,8
10679,4145,27,4,2019,20,45,23,20,0,1,3,0,64,237,8
10680,7229,27,4,2019,8,20,11,20,0,4,0,2,18,280,8
10681,12648,1,3,2019,11,30,14,10,0,10,0,5,18,238,8
10682,11753,9,5,2019,10,55,19,15,2,1,2,1,108,347,8

# Quebrando o dataset para modelagem

In [19]:
from sklearn.model_selection import train_test_split

x = dados.drop('Price', axis = 1)
y = dados['Price']

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3, random_state=42)

# Carregando o modelo

Iremos fazer o mesmo processo para os 3 modelos que falamos para verificar as diferenças

In [20]:
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score

import time

modelo_gr = GradientBoostingRegressor(
    max_depth=10,
    max_leaf_nodes=20,
    random_state=42
)

modelo_xb = XGBRegressor(
    max_depth=10,
    grow_policy="lossguide",  # Para usar max_leaves
    max_leaves=20,
    random_state=42
)

modelo_lg = LGBMRegressor(
    num_leaves=31,       # mais folhas, mais complexidade do modelo
    max_depth=-1,        # deixa ilimitado, só num_leaves controla
    learning_rate=0.05,  # menor taxa, melhora generalização
    n_estimators=1000,   # mais árvores
    boosting_type='gbdt',
    random_state=42
)



print('=========== Gradient Boosting ==============')

start = time.time()
modelo_gr.fit(x_train, y_train)
end = time.time()
y_pred_train = modelo_gr.predict(x_train)
y_pred_test = modelo_gr.predict(x_test)

print(f'O resultado na base de treino é: {r2_score(y_train,y_pred_train):.3f}')
print(f'O resultado na base de teste é: {r2_score(y_test,y_pred_test):.3f}')
print(f'O tempo que o modelo demorou para treinar foi: {end-start:.2f}')

print()
print('=========== XG Boost ==============')

start = time.time()
modelo_xb.fit(x_train, y_train)
end = time.time()
y_pred_train = modelo_xb.predict(x_train)
y_pred_test = modelo_xb.predict(x_test)


print(f'O resultado na base de treino é: {r2_score(y_train,y_pred_train):.3f}')
print(f'O resultado na base de teste é: {r2_score(y_test,y_pred_test):.3f}')
print(f'O tempo que o modelo demorou para treinar foi: {end-start:.2f}')

print()
print('=========== LGBM ==============')

start = time.time()
modelo_lg.fit(x_train, y_train)
end = time.time()
y_pred_train = modelo_lg.predict(x_train)
y_pred_test = modelo_lg.predict(x_test)

print(f'O resultado na base de treino é: {r2_score(y_train,y_pred_train):.3f}') # type: ignore
print(f'O resultado na base de teste é: {r2_score(y_test,y_pred_test):.3f}') # type: ignore
print(f'O tempo que o modelo demorou para treinar foi: {end-start:.2f}')

=========== Gradient Boosting ==============
O resultado na base de treino é: 0.935
O resultado na base de teste é: 0.893
O tempo que o modelo demorou para treinar foi: 1.13

=========== XG Boost ==============
O resultado na base de treino é: 0.969
O resultado na base de teste é: 0.896
O tempo que o modelo demorou para treinar foi: 0.21

=========== LGBM ==============
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000133 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 438
[LightGBM] [Info] Number of data points in the train set: 7478, number of used features: 13
[LightGBM] [Info] Start training from score 9121.404654
O resultado na base de treino é: 0.972
O resultado na base de teste é: 0.902
O tempo que o modelo demorou para treinar foi: 2.32

É possível ver as principais diferenças entre os modelos

- O GradientBoosting é um bom parâmetro para início

- O XGBoost traz resultados mais precisos

- O LGBM é treinado com uma velocidade muito maior

# Fazendo a Feature Selection

## Select KBest

In [21]:
from sklearn.feature_selection import SelectKBest, f_regression

In [22]:
selector = SelectKBest(score_func=f_regression, k = 7)

# Passamos todo o Dataframe para a Feature Selection, não apenas os dados de treino
selector.fit(x,y)

dados_selected = selector.transform(x)

In [23]:
dados_selected

array([[ 24,   3,  10, ...,   5,  18, 240],
       [  1,   5,  15, ...,   0,  84, 336],
       [  9,   6,  25, ...,   1, 118, 106],
       ...,
       [ 27,   4,  20, ...,   2,  18, 280],
       [  1,   3,  10, ...,   5,  18, 238],
       [  9,   5,  15, ...,   1, 108, 347]], shape=(10683, 7))

In [24]:
cols = selector.get_support(indices=True)
dados_new_best = x.iloc[:,cols]

In [25]:
dados_new_best

,day,month,arrival_min,stops,Destination_encoded,Route_encoded,Duration_encoded
0,24,3,10,0,5,18,240
1,1,5,15,2,0,84,336
2,9,6,25,2,1,118,106
3,12,5,30,1,0,91,311
4,1,3,35,1,5,29,303
...,...,...,...,...,...,...,...
10678,9,4,25,0,0,64,236
10679,27,4,20,0,0,64,237
10680,27,4,20,0,2,18,280
10681,1,3,10,0,5,18,238
10682,9,5,15,2,1,108,347

Estas são as 7 colunas (features) que mais influenciam no preço das passagens

## Select Percentile

In [26]:
from sklearn.feature_selection import SelectPercentile, f_regression


selector = SelectPercentile(score_func=f_regression,percentile=50)
selector.fit(x,y)
dados_selected = selector.transform(x)


cols = selector.get_support(indices=True)
dados_new_percentile = x.iloc[:,cols]

In [27]:
dados_new_percentile

,day,month,arrival_min,stops,Destination_encoded,Route_encoded,Duration_encoded
0,24,3,10,0,5,18,240
1,1,5,15,2,0,84,336
2,9,6,25,2,1,118,106
3,12,5,30,1,0,91,311
4,1,3,35,1,5,29,303
...,...,...,...,...,...,...,...
10678,9,4,25,0,0,64,236
10679,27,4,20,0,0,64,237
10680,27,4,20,0,2,18,280
10681,1,3,10,0,5,18,238
10682,9,5,15,2,1,108,347

# Rodando Novamente os Modelos com a Feature Selection Realizada

## Select KBest

In [28]:
x_train,x_test,y_train,y_test = train_test_split(dados_new_best,y, test_size=0.3, random_state=42)

In [29]:
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score

import time

modelo_gr = GradientBoostingRegressor(
    max_depth=10,
    max_leaf_nodes=20,
    random_state=42
)

modelo_xb = XGBRegressor(
    max_depth=10,
    grow_policy="lossguide",  # Para usar max_leaves
    max_leaves=20,
    random_state=42
)

modelo_lg = LGBMRegressor(
    num_leaves=31,       # mais folhas, mais complexidade do modelo
    max_depth=-1,        # deixa ilimitado, só num_leaves controla
    learning_rate=0.05,  # menor taxa, melhora generalização
    n_estimators=1000,   # mais árvores
    boosting_type='gbdt',
    force_col_wise=True,
    random_state=42
)

print('=========== Gradient Boosting ==============')

start = time.time()
modelo_gr.fit(x_train, y_train)
end = time.time()
y_pred_train = modelo_gr.predict(x_train)
y_pred_test = modelo_gr.predict(x_test)

print('O resultado na base de treino é: ',r2_score(y_train,y_pred_train))
print('O resultado na base de teste é: ',r2_score(y_test,y_pred_test))
print('O tempo que o modelo demorou para treinar foi: ', str(end-start))

print('=========== XG Boost ==============')

start = time.time()
modelo_xb.fit(x_train, y_train)
end = time.time()
y_pred_train = modelo_xb.predict(x_train)
y_pred_test = modelo_xb.predict(x_test)


print('O resultado na base de treino é: ',r2_score(y_train,y_pred_train))
print('O resultado na base de teste é: ',r2_score(y_test,y_pred_test))
print('O tempo que o modelo demorou para treinar foi: ', str(end-start))


print('=========== LGBM ==============')

start = time.time()
modelo_lg.fit(x_train, y_train)
end = time.time()
y_pred_train = modelo_lg.predict(x_train)
y_pred_test = modelo_lg.predict(x_test)

print('O resultado na base de treino é: ',r2_score(y_train,y_pred_train)) # type: ignore
print('O resultado na base de teste é: ',r2_score(y_test,y_pred_test)) # type: ignore
print('O tempo que o modelo demorou para treinar foi: ', str(end-start))

=========== Gradient Boosting ==============
O resultado na base de treino é:  0.8491028168273105
O resultado na base de teste é:  0.7251419119722786
O tempo que o modelo demorou para treinar foi:  0.6825263500213623
=========== XG Boost ==============
O resultado na base de treino é:  0.8950179815292358
O resultado na base de teste é:  0.7501754760742188
O tempo que o modelo demorou para treinar foi:  0.2666935920715332
=========== LGBM ==============
[LightGBM] [Info] Total Bins 355
[LightGBM] [Info] Number of data points in the train set: 7478, number of used features: 7
[LightGBM] [Info] Start training from score 9121.404654
O resultado na base de treino é:  0.8955043633690506
O resultado na base de teste é:  0.7715176828559742
O tempo que o modelo demorou para treinar foi:  0.6833596229553223

## Select Percentile

In [30]:
x_train,x_test,y_train,y_test = train_test_split(dados_new_percentile,y, test_size=0.3, random_state=42)


from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import r2_score

import time

modelo_gr = GradientBoostingRegressor(max_depth=10, max_leaf_nodes=20, random_state=42)
modelo_xb = XGBRegressor(max_depth=10,  random_state=42)
modelo_lg = LGBMRegressor(max_depth=10, force_col_wise=True, random_state=42)

print('=========== Gradient Boosting ==============')

start = time.time()
modelo_gr.fit(x_train, y_train)
end = time.time()
y_pred_train = modelo_gr.predict(x_train)
y_pred_test = modelo_gr.predict(x_test)

print('O resultado na base de treino é: ',r2_score(y_train,y_pred_train))
print('O resultado na base de teste é: ',r2_score(y_test,y_pred_test))
print('O tempo que o modelo demorou para treinar foi: ', str(end-start))

print('=========== XG Boost ==============')

start = time.time()
modelo_xb.fit(x_train, y_train)
end = time.time()
y_pred_train = modelo_xb.predict(x_train)
y_pred_test = modelo_xb.predict(x_test)


print('O resultado na base de treino é: ',r2_score(y_train,y_pred_train))
print('O resultado na base de teste é: ',r2_score(y_test,y_pred_test))
print('O tempo que o modelo demorou para treinar foi: ', str(end-start))


print('=========== LGBM ==============')

start = time.time()
modelo_lg.fit(x_train, y_train)
end = time.time()
y_pred_train = modelo_lg.predict(x_train)
y_pred_test = modelo_lg.predict(x_test)

print('O resultado na base de treino é: ',r2_score(y_train,y_pred_train)) # type: ignore
print('O resultado na base de teste é: ',r2_score(y_test,y_pred_test)) # type: ignore
print('O tempo que o modelo demorou para treinar foi: ', str(end-start))

=========== Gradient Boosting ==============
O resultado na base de treino é:  0.8491028168273105
O resultado na base de teste é:  0.7251419119722786
O tempo que o modelo demorou para treinar foi:  0.6813459396362305
=========== XG Boost ==============
O resultado na base de treino é:  0.9584424495697021
O resultado na base de teste é:  0.6513071060180664
O tempo que o modelo demorou para treinar foi:  0.4947700500488281
=========== LGBM ==============
[LightGBM] [Info] Total Bins 355
[LightGBM] [Info] Number of data points in the train set: 7478, number of used features: 7
[LightGBM] [Info] Start training from score 9121.404654
O resultado na base de treino é:  0.8250323469851006
O resultado na base de teste é:  0.763937131129601
O tempo que o modelo demorou para treinar foi:  0.09303164482116699

# Cross Validation

Pegando o modelo inicial que performou melhor, vamos testar fazer o cross validation

In [31]:
from sklearn.model_selection import train_test_split

x = dados.drop('Price', axis = 1)
y = dados['Price']

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3, random_state=42)

modelo_gb = GradientBoostingRegressor(max_depth=10, max_leaf_nodes=20, random_state=42)

print('=========== Gradient Boosting ==============')

start = time.time()
modelo_gb.fit(x_train, y_train)
end = time.time()
y_pred_train = modelo_gb.predict(x_train)
y_pred_test = modelo_gb.predict(x_test)


print('O resultado na base de treino é: ',r2_score(y_train,y_pred_train))
print('O resultado na base de teste é: ',r2_score(y_test,y_pred_test))
print('O tempo que o modelo demorou para treinar foi: ', str(end-start))

=========== Gradient Boosting ==============
O resultado na base de treino é:  0.9348709064319582
O resultado na base de teste é:  0.8934368046644536
O tempo que o modelo demorou para treinar foi:  1.0556330680847168

In [32]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import GradientBoostingRegressor 

modelo_gb = GradientBoostingRegressor(random_state=42)
parametros = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [3, 5, 8],
    'max_leaf_nodes': [20, 50, 100]
}

random_search = RandomizedSearchCV(
    estimator=modelo_gb,
    param_distributions=parametros,
    n_iter=10,  
    cv=5,
    scoring='r2',
    random_state=42 # Para garantir que os resultados sejam reproduzíveis
)

random_search.fit(x, y)

print(random_search.best_estimator_)

GradientBoostingRegressor(max_depth=5, max_leaf_nodes=100, random_state=42)

In [33]:
random_search.best_params_

{'n_estimators': 100,
 'max_leaf_nodes': 100,
 'max_depth': 5,
 'learning_rate': 0.1}

In [34]:
random_search.best_score_

np.float64(0.8805628731735402)

In [35]:
melhor_modelo = random_search.best_estimator_

# Salvando nosso Modelo

In [36]:
import pickle

arquivo_modelo = 'modelo.sav'

pickle.dump(melhor_modelo, open(arquivo_modelo, 'wb'))

# Carregando o modelo Salvo

In [37]:
modelo_carregado = pickle.load(open(arquivo_modelo, 'rb'))

# Codigo novo que roda todos os dias

In [38]:
# Importação das bibliotecas

# Tratamento dos dados
# Feature Selection se aplicável
# Carregamento do modelo já treinado
# Previsão e disponibilização dos dados novos já com previsão

In [39]:
y_pred_test = modelo_carregado.predict(x_test)
print('O resultado na base de teste é: ',r2_score(y_test,y_pred_test))

O resultado na base de teste é:  0.9169114600975511

Mas o que significam wb e rb?


Basicamente é forma que estamos usando o arquivo.


Quando estamos usando o método dump, estamos escrevendo(salvando) um arquivo, então wb significa write byte. Em resumo estamos passando privilégios de escrita.
No caso do carregamento estamos fazendo leitura, então usando read ao invés de write.


No momento de dizer o nome do arquivo como "modelo.sav" podemos passar uma path ou caminho inteiro no computador, para salvar o modelo em alguma pasta específica. Neste caso passamos apenas o nome do arquivo, isso significa que o modelo será salvo na mesma pasta que o notebook.


O modelo sempre é salvo pós treinamento, então ele já guarda tudo que aprendeu com o treinamento.

Use sempre esta alternativa quando conseguir um modelo com bons resultados para não ter que passar pelo tempo de treinamento novamente, principalmente quando for necessário um grande tempo para treinar seu modelo.

Dessa forma é possível automatizar fluxos de dados, chamando direto o modelo treinado e pedindo um resultado predict, para saber a predição. Sem precisar treinar o modelo com novos dados toda vez.

Mesmo assim é uma boa prática de tempos em tempos rever se seu modelo ainda está performando bem e se não precisa ser treinado novamente, principalmente quando a característica dos seus dados vai mudando ao longo do tempo.